services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ broker
      - "15672:15672" # RabbitMQ management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  main:
    build:
      context: main
    depends_on:
      - rabbitmq

  detectron:
    build:
      context: detectron
    depends_on:
      - main

  yolo:
    build:
      context: yolo
    depends_on:
      - main
